window.GAMES = [
  {
    "title": "Minecraft",
    "genres": ["Sandbox", "Survival"],
    "rating": 4.8,
    "price": 29.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2011,
    "developer": "Mojang Studios",
    "publisher": "Mojang Studios",
    "description": "A sandbox game where players can build, explore, and survive in a blocky infinite world.",
    "tags": ["Creative", "Survival", "Multiplayer", "Building"],
    "image": "https://via.placeholder.com/300x400?text=Minecraft"
  },
  {
    "title": "Grand Theft Auto V",
    "genres": ["Action", "Open World"],
    "rating": 4.7,
    "price": 29.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2013,
    "developer": "Rockstar North",
    "publisher": "Rockstar Games",
    "description": "An open-world crime game following three characters in the city of Los Santos.",
    "tags": ["Crime", "Open World", "Story", "Multiplayer"],
    "image": "https://via.placeholder.com/300x400?text=GTA+V"
  },
  {
    "title": "Red Dead Redemption 2",
    "genres": ["Action", "Adventure", "Open World"],
    "rating": 4.9,
    "price": 59.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2018,
    "developer": "Rockstar Games",
    "publisher": "Rockstar Games",
    "description": "A story-driven Western adventure in a massive open world.",
    "tags": ["Western", "Story Rich", "Open World", "Realistic"],
    "image": "https://via.placeholder.com/300x400?text=RDR2"
  },
  {
    "title": "Elden Ring",
    "genres": ["Action RPG", "Open World"],
    "rating": 4.9,
    "price": 59.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2022,
    "developer": "FromSoftware",
    "publisher": "Bandai Namco",
    "description": "A vast fantasy world filled with dangerous enemies and legendary bosses.",
    "tags": ["Soulslike", "Hard", "Fantasy", "Boss Battles"],
    "image": "https://via.placeholder.com/300x400?text=Elden+Ring"
  },
  {
    "title": "Cyberpunk 2077",
    "genres": ["RPG", "Open World"],
    "rating": 4.5,
    "price": 49.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2020,
    "developer": "CD Projekt Red",
    "publisher": "CD Projekt",
    "description": "A futuristic RPG set in the neon city of Night City.",
    "tags": ["Sci-Fi", "Cyberpunk", "Story Rich", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=Cyberpunk+2077"
  },
  {
    "title": "The Witcher 3: Wild Hunt",
    "genres": ["RPG", "Open World"],
    "rating": 4.9,
    "price": 39.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2015,
    "developer": "CD Projekt Red",
    "publisher": "CD Projekt",
    "description": "You play as Geralt, a monster hunter searching for his adopted daughter.",
    "tags": ["Fantasy", "Story Rich", "Choices Matter", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=Witcher+3"
  },
  {
    "title": "Valorant",
    "genres": ["FPS", "Tactical Shooter"],
    "rating": 4.6,
    "price": 0,
    "platforms": ["PC"],
    "releaseYear": 2020,
    "developer": "Riot Games",
    "publisher": "Riot Games",
    "description": "A competitive tactical shooter with unique agent abilities.",
    "tags": ["Competitive", "Esports", "Multiplayer", "Shooter"],
    "image": "https://via.placeholder.com/300x400?text=Valorant"
  },
  {
    "title": "Counter-Strike 2",
    "genres": ["FPS", "Competitive"],
    "rating": 4.7,
    "price": 0,
    "platforms": ["PC"],
    "releaseYear": 2023,
    "developer": "Valve",
    "publisher": "Valve",
    "description": "The latest version of the legendary tactical shooter.",
    "tags": ["Esports", "Multiplayer", "Shooter", "Tactical"],
    "image": "https://via.placeholder.com/300x400?text=CS2"
  },
  {
    "title": "Fortnite",
    "genres": ["Battle Royale", "Shooter"],
    "rating": 4.5,
    "price": 0,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2017,
    "developer": "Epic Games",
    "publisher": "Epic Games",
    "description": "A fast-paced battle royale with building mechanics.",
    "tags": ["Battle Royale", "Multiplayer", "Shooter", "Building"],
    "image": "https://via.placeholder.com/300x400?text=Fortnite"
  },
  {
    "title": "Apex Legends",
    "genres": ["Battle Royale", "FPS"],
    "rating": 4.6,
    "price": 0,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2019,
    "developer": "Respawn Entertainment",
    "publisher": "Electronic Arts",
    "description": "A hero-based battle royale shooter.",
    "tags": ["Multiplayer", "Competitive", "Battle Royale", "Team Based"],
    "image": "https://via.placeholder.com/300x400?text=Apex+Legends"
  },
  {
    "title": "Hollow Knight",
    "genres": ["Metroidvania", "Indie"],
    "rating": 4.9,
    "price": 14.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2017,
    "developer": "Team Cherry",
    "publisher": "Team Cherry",
    "description": "A dark and atmospheric action-adventure in a vast underground world.",
    "tags": ["Indie", "Exploration", "Hard", "2D"],
    "image": "https://via.placeholder.com/300x400?text=Hollow+Knight"
  },
  {
    "title": "Hades",
    "genres": ["Roguelike", "Action"],
    "rating": 4.9,
    "price": 24.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2020,
    "developer": "Supergiant Games",
    "publisher": "Supergiant Games",
    "description": "Battle out of the underworld as the son of Hades.",
    "tags": ["Roguelike", "Fast Paced", "Indie", "Mythology"],
    "image": "https://via.placeholder.com/300x400?text=Hades"
  },
  {
    "title": "Ghost of Tsushima",
    "genres": ["Action", "Adventure", "Open World"],
    "rating": 4.8,
    "price": 59.99,
    "platforms": ["PlayStation", "PC"],
    "releaseYear": 2020,
    "developer": "Sucker Punch Productions",
    "publisher": "Sony Interactive Entertainment",
    "description": "A samurai action game set during the Mongol invasion of Japan.",
    "tags": ["Samurai", "Open World", "Stealth", "Story Rich"],
    "image": "https://via.placeholder.com/300x400?text=Ghost+of+Tsushima"
  },
  {
    "title": "God of War",
    "genres": ["Action", "Adventure"],
    "rating": 4.9,
    "price": 49.99,
    "platforms": ["PlayStation", "PC"],
    "releaseYear": 2018,
    "developer": "Santa Monica Studio",
    "publisher": "Sony Interactive Entertainment",
    "description": "Kratos journeys with his son through Norse mythology.",
    "tags": ["Mythology", "Story Rich", "Combat", "Adventure"],
    "image": "https://via.placeholder.com/300x400?text=God+of+War"
  },
  {
    "title": "God of War RagnarÃ¶k",
    "genres": ["Action", "Adventure"],
    "rating": 4.9,
    "price": 69.99,
    "platforms": ["PlayStation"],
    "releaseYear": 2022,
    "developer": "Santa Monica Studio",
    "publisher": "Sony Interactive Entertainment",
    "description": "Kratos and Atreus face the end of the Norse world.",
    "tags": ["Mythology", "Story Rich", "Combat", "Sequel"],
    "image": "https://via.placeholder.com/300x400?text=GoW+Ragnarok"
  },
  {
    "title": "Sekiro: Shadows Die Twice",
    "genres": ["Action", "Soulslike"],
    "rating": 4.8,
    "price": 59.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2019,
    "developer": "FromSoftware",
    "publisher": "Activision",
    "description": "A challenging samurai combat game focused on precision and timing.",
    "tags": ["Hard", "Samurai", "Boss Battles", "Soulslike"],
    "image": "https://via.placeholder.com/300x400?text=Sekiro"
  },
  {
    "title": "Dark Souls III",
    "genres": ["Action RPG", "Soulslike"],
    "rating": 4.8,
    "price": 39.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2016,
    "developer": "FromSoftware",
    "publisher": "Bandai Namco",
    "description": "A dark fantasy action RPG known for its difficulty.",
    "tags": ["Hard", "Dark Fantasy", "Boss Battles", "RPG"],
    "image": "https://via.placeholder.com/300x400?text=Dark+Souls+3"
  },
  {
    "title": "Dark Souls Remastered",
    "genres": ["Action RPG", "Soulslike"],
    "rating": 4.7,
    "price": 39.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2018,
    "developer": "FromSoftware",
    "publisher": "Bandai Namco",
    "description": "The remastered version of the iconic dark fantasy RPG.",
    "tags": ["Hard", "Classic", "Dark Fantasy", "RPG"],
    "image": "https://via.placeholder.com/300x400?text=Dark+Souls+Remastered"
  },
  {
    "title": "Elden Ring: Shadow of the Erdtree",
    "genres": ["Action RPG", "DLC"],
    "rating": 4.9,
    "price": 39.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2024,
    "developer": "FromSoftware",
    "publisher": "Bandai Namco",
    "description": "Expansion to Elden Ring with new lands and bosses.",
    "tags": ["Soulslike", "Expansion", "Fantasy", "Hard"],
    "image": "https://via.placeholder.com/300x400?text=Elden+Ring+DLC"
  },
  {
    "title": "Starfield",
    "genres": ["RPG", "Sci-Fi", "Open World"],
    "rating": 4.4,
    "price": 69.99,
    "platforms": ["PC", "Xbox"],
    "releaseYear": 2023,
    "developer": "Bethesda Game Studios",
    "publisher": "Bethesda Softworks",
    "description": "A space exploration RPG set among the stars.",
    "tags": ["Space", "Exploration", "Sci-Fi", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=Starfield"
  },
  {
    "title": "No Man's Sky",
    "genres": ["Survival", "Sci-Fi"],
    "rating": 4.6,
    "price": 59.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2016,
    "developer": "Hello Games",
    "publisher": "Hello Games",
    "description": "Explore an infinite universe of procedurally generated planets.",
    "tags": ["Space", "Exploration", "Survival", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=No+Mans+Sky"
  },
  {
    "title": "Subnautica",
    "genres": ["Survival", "Exploration"],
    "rating": 4.8,
    "price": 29.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2018,
    "developer": "Unknown Worlds Entertainment",
    "publisher": "Unknown Worlds Entertainment",
    "description": "Survive on an alien ocean planet filled with mystery.",
    "tags": ["Underwater", "Survival", "Exploration", "Atmospheric"],
    "image": "https://via.placeholder.com/300x400?text=Subnautica"
  },
  {
    "title": "Subnautica: Below Zero",
    "genres": ["Survival", "Exploration"],
    "rating": 4.6,
    "price": 29.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2021,
    "developer": "Unknown Worlds Entertainment",
    "publisher": "Unknown Worlds Entertainment",
    "description": "A cold, alien ocean survival experience.",
    "tags": ["Underwater", "Survival", "Ice", "Exploration"],
    "image": "https://via.placeholder.com/300x400?text=Below+Zero"
  },
  {
    "title": "Project Zomboid",
    "genres": ["Survival", "Zombie"],
    "rating": 4.7,
    "price": 19.99,
    "platforms": ["PC"],
    "releaseYear": 2013,
    "developer": "The Indie Stone",
    "publisher": "The Indie Stone",
    "description": "A hardcore zombie survival simulation game.",
    "tags": ["Zombie", "Survival", "Hardcore", "Multiplayer"],
    "image": "https://via.placeholder.com/300x400?text=Project+Zomboid"
  },
  {
    "title": "DayZ",
    "genres": ["Survival", "Multiplayer"],
    "rating": 4.3,
    "price": 44.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2018,
    "developer": "Bohemia Interactive",
    "publisher": "Bohemia Interactive",
    "description": "A brutal multiplayer survival game in a zombie apocalypse.",
    "tags": ["Zombie", "Multiplayer", "Survival", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=DayZ"
  },
  {
    "title": "Rust",
    "genres": ["Survival", "Multiplayer"],
    "rating": 4.6,
    "price": 39.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2018,
    "developer": "Facepunch Studios",
    "publisher": "Facepunch Studios",
    "description": "A brutal multiplayer survival game where players fight to survive.",
    "tags": ["PvP", "Survival", "Crafting", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=Rust"
  },
  {
    "title": "The Forest",
    "genres": ["Survival", "Horror"],
    "rating": 4.6,
    "price": 19.99,
    "platforms": ["PC", "PlayStation"],
    "releaseYear": 2018,
    "developer": "Endnight Games",
    "publisher": "Endnight Games",
    "description": "Survive on a cannibal-infested island after a plane crash.",
    "tags": ["Horror", "Survival", "Crafting", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=The+Forest"
  },
  {
    "title": "Sons of the Forest",
    "genres": ["Survival", "Horror"],
    "rating": 4.5,
    "price": 29.99,
    "platforms": ["PC"],
    "releaseYear": 2023,
    "developer": "Endnight Games",
    "publisher": "Newnight",
    "description": "A sequel to The Forest with improved survival mechanics.",
    "tags": ["Horror", "Survival", "Crafting", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=Sons+of+the+Forest"
  },
  {
    "title": "Phasmophobia",
    "genres": ["Horror", "Co-op"],
    "rating": 4.7,
    "price": 13.99,
    "platforms": ["PC", "VR"],
    "releaseYear": 2020,
    "developer": "Kinetic Games",
    "publisher": "Kinetic Games",
    "description": "A cooperative ghost-hunting horror game.",
    "tags": ["Ghosts", "Co-op", "Horror", "VR"],
    "image": "https://via.placeholder.com/300x400?text=Phasmophobia"
  },
  {
    "title": "Lethal Company",
    "genres": ["Horror", "Co-op"],
    "rating": 4.8,
    "price": 9.99,
    "platforms": ["PC"],
    "releaseYear": 2023,
    "developer": "Zeekerss",
    "publisher": "Zeekerss",
    "description": "A co-op horror scavenging game with deadly monsters.",
    "tags": ["Co-op", "Horror", "Indie", "Survival"],
    "image": "https://via.placeholder.com/300x400?text=Lethal+Company"
  },
  {
    "title": "Dead by Daylight",
    "genres": ["Horror", "Multiplayer"],
    "rating": 4.5,
    "price": 19.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2016,
    "developer": "Behaviour Interactive",
    "publisher": "Behaviour Interactive",
    "description": "A multiplayer horror game where one player is the killer.",
    "tags": ["Asymmetrical", "Horror", "Multiplayer", "Survival"],
    "image": "https://via.placeholder.com/300x400?text=Dead+by+Daylight"
  },
  {
    "title": "Among Us",
    "genres": ["Multiplayer", "Party"],
    "rating": 4.4,
    "price": 4.99,
    "platforms": ["PC", "Mobile", "Switch"],
    "releaseYear": 2018,
    "developer": "InnerSloth",
    "publisher": "InnerSloth",
    "description": "A social deduction game where impostors try to eliminate crewmates.",
    "tags": ["Social", "Multiplayer", "Party", "Deduction"],
    "image": "https://via.placeholder.com/300x400?text=Among+Us"
  },
  {
    "title": "Fall Guys",
    "genres": ["Party", "Battle Royale"],
    "rating": 4.3,
    "price": 0,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2020,
    "developer": "Mediatonic",
    "publisher": "Epic Games",
    "description": "A chaotic party battle royale with obstacle courses.",
    "tags": ["Funny", "Multiplayer", "Party", "Battle Royale"],
    "image": "https://via.placeholder.com/300x400?text=Fall+Guys"
  },
  {
    "title": "Rocket League",
    "genres": ["Sports", "Racing"],
    "rating": 4.8,
    "price": 0,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2015,
    "developer": "Psyonix",
    "publisher": "Psyonix",
    "description": "Soccer but with rocket-powered cars.",
    "tags": ["Competitive", "Multiplayer", "Cars", "Sports"],
    "image": "https://via.placeholder.com/300x400?text=Rocket+League"
  },
  {
    "title": "Forza Horizon 5",
    "genres": ["Racing", "Open World"],
    "rating": 4.8,
    "price": 59.99,
    "platforms": ["PC", "Xbox"],
    "releaseYear": 2021,
    "developer": "Playground Games",
    "publisher": "Xbox Game Studios",
    "description": "An open-world racing game set in Mexico.",
    "tags": ["Cars", "Racing", "Open World", "Simulation"],
    "image": "https://via.placeholder.com/300x400?text=Forza+Horizon+5"
  },
  {
    "title": "Need for Speed Heat",
    "genres": ["Racing"],
    "rating": 4.4,
    "price": 59.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2019,
    "developer": "Ghost Games",
    "publisher": "Electronic Arts",
    "description": "Street racing in a vibrant open-world city.",
    "tags": ["Cars", "Racing", "Police Chases", "Arcade"],
    "image": "https://via.placeholder.com/300x400?text=NFS+Heat"
  },
  {
    "title": "Euro Truck Simulator 2",
    "genres": ["Simulation", "Driving"],
    "rating": 4.8,
    "price": 19.99,
    "platforms": ["PC"],
    "releaseYear": 2012,
    "developer": "SCS Software",
    "publisher": "SCS Software",
    "description": "Drive trucks across Europe in a realistic simulation.",
    "tags": ["Driving", "Relaxing", "Simulation", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=ETS2"
  },
  {
    "title": "Assetto Corsa",
    "genres": ["Racing", "Simulation"],
    "rating": 4.7,
    "price": 19.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2014,
    "developer": "Kunos Simulazioni",
    "publisher": "505 Games",
    "description": "A realistic racing simulator focused on driving physics.",
    "tags": ["Cars", "Simulation", "Realistic", "Racing"],
    "image": "https://via.placeholder.com/300x400?text=Assetto+Corsa"
  },
  {
    "title": "BeamNG.drive",
    "genres": ["Simulation", "Driving"],
    "rating": 4.8,
    "price": 24.99,
    "platforms": ["PC"],
    "releaseYear": 2015,
    "developer": "BeamNG",
    "publisher": "BeamNG",
    "description": "A physics-based driving simulator with realistic crashes.",
    "tags": ["Physics", "Cars", "Simulation", "Sandbox"],
    "image": "https://via.placeholder.com/300x400?text=BeamNG"
  },
  {
    "title": "Cities: Skylines",
    "genres": ["Simulation", "City Builder"],
    "rating": 4.8,
    "price": 29.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2015,
    "developer": "Colossal Order",
    "publisher": "Paradox Interactive",
    "description": "Build and manage your own city from the ground up.",
    "tags": ["City Builder", "Simulation", "Strategy", "Sandbox"],
    "image": "https://via.placeholder.com/300x400?text=Cities+Skylines"
  },
  {
    "title": "Cities: Skylines II",
    "genres": ["Simulation", "City Builder"],
    "rating": 4.4,
    "price": 49.99,
    "platforms": ["PC"],
    "releaseYear": 2023,
    "developer": "Colossal Order",
    "publisher": "Paradox Interactive",
    "description": "A modern city-building simulation with improved systems.",
    "tags": ["City Builder", "Simulation", "Strategy"],
    "image": "https://via.placeholder.com/300x400?text=Cities+Skylines+2"
  },
  {
    "title": "Planet Zoo",
    "genres": ["Simulation"],
    "rating": 4.7,
    "price": 44.99,
    "platforms": ["PC"],
    "releaseYear": 2019,
    "developer": "Frontier Developments",
    "publisher": "Frontier Developments",
    "description": "Build and manage a realistic zoo ecosystem.",
    "tags": ["Animals", "Simulation", "Management"],
    "image": "https://via.placeholder.com/300x400?text=Planet+Zoo"
  },
  {
    "title": "Planet Coaster",
    "genres": ["Simulation"],
    "rating": 4.6,
    "price": 39.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2016,
    "developer": "Frontier Developments",
    "publisher": "Frontier Developments",
    "description": "Design and manage your own theme park.",
    "tags": ["Theme Park", "Simulation", "Creative"],
    "image": "https://via.placeholder.com/300x400?text=Planet+Coaster"
  },
  {
    "title": "Farming Simulator 22",
    "genres": ["Simulation"],
    "rating": 4.5,
    "price": 39.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2021,
    "developer": "GIANTS Software",
    "publisher": "GIANTS Software",
    "description": "Realistic farming simulation with vehicles and crops.",
    "tags": ["Farming", "Simulation", "Vehicles"],
    "image": "https://via.placeholder.com/300x400?text=Farming+Sim+22"
  },
  {
    "title": "Microsoft Flight Simulator",
    "genres": ["Simulation"],
    "rating": 4.8,
    "price": 59.99,
    "platforms": ["PC", "Xbox"],
    "releaseYear": 2020,
    "developer": "Asobo Studio",
    "publisher": "Xbox Game Studios",
    "description": "A highly realistic flight simulation of the entire Earth.",
    "tags": ["Planes", "Realistic", "Simulation", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=Flight+Sim"
  },
  {
    "title": "House Flipper",
    "genres": ["Simulation"],
    "rating": 4.4,
    "price": 24.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2018,
    "developer": "Empyrean",
    "publisher": "Frozen District",
    "description": "Buy, renovate, and sell houses for profit.",
    "tags": ["Renovation", "Simulation", "Creative"],
    "image": "https://via.placeholder.com/300x400?text=House+Flipper"
  },
  {
    "title": "PowerWash Simulator",
    "genres": ["Simulation"],
    "rating": 4.7,
    "price": 19.99,
    "platforms": ["PC", "PlayStation", "Xbox", "Switch"],
    "releaseYear": 2022,
    "developer": "FuturLab",
    "publisher": "Square Enix",
    "description": "Relaxing simulator where you clean dirty environments.",
    "tags": ["Relaxing", "Simulation", "Cleaning"],
    "image": "https://via.placeholder.com/300x400?text=PowerWash"
  },
  {
    "title": "Teardown",
    "genres": ["Sandbox", "Simulation"],
    "rating": 4.6,
    "price": 29.99,
    "platforms": ["PC"],
    "releaseYear": 2020,
    "developer": "Tuxedo Labs",
    "publisher": "Tuxedo Labs",
    "description": "A destruction-based sandbox game with full physics.",
    "tags": ["Destruction", "Physics", "Sandbox"],
    "image": "https://via.placeholder.com/300x400?text=Teardown"
  },
  {
    "title": "Garry's Mod",
    "genres": ["Sandbox"],
    "rating": 4.8,
    "price": 9.99,
    "platforms": ["PC"],
    "releaseYear": 2006,
    "developer": "Facepunch Studios",
    "publisher": "Valve",
    "description": "A physics sandbox game with unlimited creativity.",
    "tags": ["Sandbox", "Multiplayer", "Creative"],
    "image": "https://via.placeholder.com/300x400?text=Garrys+Mod"
  },
  {
    "title": "Factorio",
    "genres": ["Strategy", "Automation"],
    "rating": 4.9,
    "price": 35.00,
    "platforms": ["PC"],
    "releaseYear": 2020,
    "developer": "Wube Software",
    "publisher": "Wube Software",
    "description": "Build and optimize automated factories.",
    "tags": ["Automation", "Strategy", "Base Building"],
    "image": "https://via.placeholder.com/300x400?text=Factorio"
  },
  {
    "title": "Satisfactory",
    "genres": ["Automation", "Sandbox"],
    "rating": 4.8,
    "price": 29.99,
    "platforms": ["PC"],
    "releaseYear": 2020,
    "developer": "Coffee Stain Studios",
    "publisher": "Coffee Stain Publishing",
    "description": "A first-person factory building and automation game.",
    "tags": ["Automation", "Exploration", "Sandbox"],
    "image": "https://via.placeholder.com/300x400?text=Satisfactory"
  },
  {
    "title": "RimWorld",
    "genres": ["Simulation", "Strategy"],
    "rating": 4.9,
    "price": 34.99,
    "platforms": ["PC"],
    "releaseYear": 2018,
    "developer": "Ludeon Studios",
    "publisher": "Ludeon Studios",
    "description": "A colony simulation driven by AI storytelling.",
    "tags": ["Survival", "Base Building", "Strategy"],
    "image": "https://via.placeholder.com/300x400?text=RimWorld"
  },
  {
    "title": "Stellaris",
    "genres": ["Strategy", "Sci-Fi"],
    "rating": 4.7,
    "price": 39.99,
    "platforms": ["PC"],
    "releaseYear": 2016,
    "developer": "Paradox Interactive",
    "publisher": "Paradox Interactive",
    "description": "A grand strategy game set in space civilizations.",
    "tags": ["Space", "Strategy", "Empire Building"],
    "image": "https://via.placeholder.com/300x400?text=Stellaris"
  },
  {
    "title": "Crusader Kings III",
    "genres": ["Strategy"],
    "rating": 4.8,
    "price": 49.99,
    "platforms": ["PC"],
    "releaseYear": 2020,
    "developer": "Paradox Interactive",
    "publisher": "Paradox Interactive",
    "description": "A medieval dynasty simulator focused on politics and war.",
    "tags": ["Medieval", "Strategy", "Dynasty"],
    "image": "https://via.placeholder.com/300x400?text=CK3"
  },
  {
    "title": "Age of Empires IV",
    "genres": ["Strategy", "RTS"],
    "rating": 4.7,
    "price": 59.99,
    "platforms": ["PC"],
    "releaseYear": 2021,
    "developer": "Relic Entertainment",
    "publisher": "Xbox Game Studios",
    "description": "A real-time strategy game based on historical civilizations.",
    "tags": ["RTS", "Strategy", "War"],
    "image": "https://via.placeholder.com/300x400?text=AoE4"
  },
  {
    "title": "Hearts of Iron IV",
    "genres": ["Strategy", "War"],
    "rating": 4.7,
    "price": 39.99,
    "platforms": ["PC"],
    "releaseYear": 2016,
    "developer": "Paradox Interactive",
    "publisher": "Paradox Interactive",
    "description": "A WWII grand strategy game focused on global warfare.",
    "tags": ["WW2", "Strategy", "War"],
    "image": "https://via.placeholder.com/300x400?text=HOI4"
  },
  {
    "title": "Northgard",
    "genres": ["Strategy", "RTS"],
    "rating": 4.6,
    "price": 29.99,
    "platforms": ["PC"],
    "releaseYear": 2018,
    "developer": "Shiro Games",
    "publisher": "Shiro Games",
    "description": "A Viking-themed real-time strategy game.",
    "tags": ["Vikings", "RTS", "Strategy"],
    "image": "https://via.placeholder.com/300x400?text=Northgard"
  },
  {
    "title": "Dishonored 2",
    "genres": ["Action", "Stealth"],
    "rating": 4.7,
    "price": 29.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2016,
    "developer": "Arkane Studios",
    "publisher": "Bethesda Softworks",
    "description": "A stealth-action game with supernatural abilities.",
    "tags": ["Stealth", "Assassination", "Story"],
    "image": "https://via.placeholder.com/300x400?text=Dishonored+2"
  },
  {
    "title": "Metal Gear Solid V",
    "genres": ["Action", "Stealth"],
    "rating": 4.8,
    "price": 19.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2015,
    "developer": "Kojima Productions",
    "publisher": "Konami",
    "description": "A tactical espionage game with open-world freedom.",
    "tags": ["Stealth", "Espionage", "Open World"],
    "image": "https://via.placeholder.com/300x400?text=MGSV"
  },
  {
    "title": "Hitman 3",
    "genres": ["Stealth", "Action"],
    "rating": 4.7,
    "price": 49.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2021,
    "developer": "IO Interactive",
    "publisher": "IO Interactive",
    "description": "Become Agent 47 in a sandbox assassination game.",
    "tags": ["Stealth", "Assassination", "Sandbox"],
    "image": "https://via.placeholder.com/300x400?text=Hitman+3"
  },
  {
    "title": "Control",
    "genres": ["Action", "Supernatural"],
    "rating": 4.6,
    "price": 29.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2019,
    "developer": "Remedy Entertainment",
    "publisher": "505 Games",
    "description": "A supernatural action game set in a mysterious government building.",
    "tags": ["Supernatural", "Story Rich", "Action"],
    "image": "https://via.placeholder.com/300x400?text=Control"
  },
  {
    "title": "Alan Wake 2",
    "genres": ["Horror", "Action"],
    "rating": 4.8,
    "price": 59.99,
    "platforms": ["PC", "PlayStation", "Xbox"],
    "releaseYear": 2023,
    "developer": "Remedy Entertainment",
    "publisher": "Epic Games",
    "description": "A psychological horror thriller with dual protagonists.",
    "tags": ["Horror", "Psychological", "Story Rich"],
    "image": "https://via.placeholder.com/300x400?text=Alan+Wake+2"
  },
  {
    "title": "Death Stranding",
    "genres": ["Adventure", "Sci-Fi"],
    "rating": 4.6,
    "price": 39.99,
    "platforms": ["PC", "PlayStation"],
    "releaseYear": 2019,
    "developer": "Kojima Productions",
    "publisher": "Sony Interactive Entertainment",
    "description": "A unique delivery-based open-world experience.",
    "tags": ["Walking Simulator", "Story", "Sci-Fi"],
    "image": "https://via.placeholder.com/300x400?text=Death+Stranding"
  }
];
